[package]
name = "fm-tui"
version = "0.1.10"
authors = ["Quentin Konieczko <qu3nt1n@gmail.com>"]
edition = "2021"
license-file = "LICENSE.txt"
description = "A TUI file manager inspired by dired and ranger"
readme = "readme.md"
repository = "https://github.com/qkzk/fm"
keywords = ["tui", "file-manager", "file", "manager", "tuikit"]
categories = ["command-line-utilities", "filesystem", "os::unix-apis"]
documentation = "https://docs.rs/fm-tui/latest/"

[profile.release]
strip = true  # Automatically strip symbols from the binary.
lto = true # instructs the linker to optimize at the link stage.

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[[bin]]
name = "fm"
path = "src/main.rs"

[lib]
name = "fm"
path = "src/lib.rs"

[build-dependencies]
shellexpand = "2.1.2"
fs_extra = "1.2.0"

[dependencies]
chrono = "0.4.22"
clap = { version = "4.0.2", features = ["derive"] }
compress-tools = "0.14.0"
content_inspector = "0.2.4"
copypasta = "0.8.1"
fs_extra = "1.2.0"
image = "0.24.5"
indicatif = { version = "0.17.1", features= ["in_memory"] }
kamadak-exif = "0.5.5"
log = { version = "0.4.0", features = ["std"] }
log4rs = {version = "1.2.0", features = ["rolling_file_appender", "compound_policy", "size_trigger", "fixed_window_roller"] }
notify-rust = "4.5.10"
pdf-extract = "0.6.4"
rand = "0.8.5"
regex = "1.6.0"
sanitize-filename = "0.4.0"
serde_yaml = "0.9.13"
shellexpand = "2.1.2"
skim-qkzk = "0.9.9"
strfmt = "0.2.2"
strum = {version = "0.24.1", features = ["derive"]}
strum_macros = "0.24.3"
syntect = "5.0.0"
sysinfo = "0.26.7"
tuikit = "0.5.0"
url-escape = "0.1.1"
users = "0.11.0"
