[package]
name = "fm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[[bin]]
name = "fm"
path = "src/main.rs"

[lib]
name = "fm"
path = "src/lib.rs"

[dependencies]
chrono = "*"
regex = "1"
serde_yaml = "0.9.13"
shellexpand = "2.1.2"
tuikit = "*"
users = "0.11.0"
