[package]
name = "fm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[[bin]]
name = "fm"
path = "src/main.rs"

[lib]
name = "fm"
path = "src/lib.rs"

[dependencies]
chrono = "*"
clap = { version = "4.0", features = ["derive"] }
regex = "1"
serde_yaml = "0.9.13"
shellexpand = "2.1.2"
syntect = "5.0"
tuikit = "*"
users = "0.11.0"
content_inspector = "0.2.4"
skim = { git = "https://github.com/qkzk/skim", branch="test" }
