[package]
name = "fm"
version = "0.1.0"
authors = ["Quentin Konieczko <qu3nt1n@gmail.com>"]
edition = "2021"

[profile.release]
strip = true  # Automatically strip symbols from the binary.
lto = true # instructs the linker to optimize at the link stage.

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[[bin]]
name = "fm"
path = "src/main.rs"

[lib]
name = "fm"
path = "src/lib.rs"

[dependencies]
chrono = "*"
clap = { version = "4.0", features = ["derive"] }
content_inspector = "0.2.4"
copypasta = "0.8.1"
fs_extra = "1.2.0"
indicatif = { version = "0.17.1", features= ["in_memory"] }
kamadak-exif = "0.5.5"
log = { version = "0.4.0", features = ["std"] }
log4rs = {version = "1.2.0", features = ["rolling_file_appender", "compound_policy", "size_trigger", "fixed_window_roller"] }
notify-rust = "4"
pdf-extract = "0.6.4"
rand = "^0"
regex = "1"
serde_yaml = "0.9.13"
shellexpand = "2.1.2"
skim = { git = "https://github.com/qkzk/skim" }
syntect = "5.0"
sysinfo = "0.26.7"
tuikit = "*"
users = "0.11.0"
zip = "0.6.3"
