# the terminal must be installed
terminal: st
colors:
  # white, black, red, green, blue, yellow, cyan, magenta 
  # light_white, light_black, light_red, light_green, light_blue, light_yellow, light_cyan, light_magenta 
  file: white
  directory: red
  block: yellow
  char: green
  fifo: blue
  socket: cyan
  symlink: magenta
keybindings:
  # only ASCII char keys are allowed
  # non ASCII letters char must be in single quotes like this '*'
  a: ToggleHidden
  c: CopyPaste
  p: CutPaste
  x: DeleteFile
  m: Chmod
  e: Exec
  d: NewDir
  n: NewFile
  r: Rename
  u: ClearFlags
  " " : ToggleFlag
  s: Shell
  o: OpenFile
  h: Help
  "/": Search
  g: Goto
  "*": FlagAll
  W: RegexMatch
  j: Jump
  i: NvimFilepicker
  O: Sort
  S: Symlink
  P: Preview
  H: History
  M: MarksNew
  "'": MarksJump
  k: Shell
  G: Shortcut
