# the terminal must be installed
terminal: st
colors:
  # white, black, red, green, blue, yellow, cyan, magenta 
  # light_white, light_black, light_red, light_green, light_blue, light_yellow, light_cyan, light_magenta 
  file: white
  directory: red
  block: yellow
  char: green
  fifo: blue
  socket: cyan
  symlink: magenta
keybindings:
  # only ASCII char keys are allowed
  # ASCII letters must be lowercase
  # non ASCII letters char must be in single quotes like this '*'
  toggle_hidden: a
  copy_paste: c
  cut_paste: p
  delete: x
  chmod: m
  exec: e
  newdir: d
  newfile: n
  rename: r
  clear_flags: u
  toggle_flag: ' '
  shell: s
  open_file: o
  help: h
  search: '/'
  quit: q
  goto: g
  flag_all: '*'
  reverse_flags: v
  regex_match: w
  jump: j
  nvim: i
  sort_by: O
  symlink: S
  preview: P
  history: H
