appenders:
  normal_logger:
    kind: rolling_file
    path: "$ENV{HOME}/.config/fm/log/fm.log"
    encoder:
      pattern: "{d(%Y-%m-%d %H:%M:%S)} - {m}{n}"
    policy:
      trigger:
        kind: size
        limit: 50kb
      roller:
        kind: delete
  action_logger:
    kind: rolling_file
    path: "$ENV{HOME}/.config/fm/log/action_logger.log"
    encoder:
      pattern: "{d(%Y-%m-%d %H:%M:%S)} - {m}{n}"
    policy:
      trigger:
        kind: size
        limit: 50kb
      roller:
        kind: delete
root:
  level: info
  appenders:
    - normal_logger
loggers:
  special:
    level: info
    appenders:
      - action_logger
    additive: false
