# Gradient from start to stop for normal files.
# the files are colored randomly according to their extension
# ANSI colors won't be linked to their configured values but to the default ANSI values.
normal_start: rgb(187, 102, 255)
normal_stop: rgb(255, 102, 187)

# color for different filekinds
# here you can use ANSI values
# colors for folders / directory
directory: rgb(45, 250, 209)
# block device (hard drives...)
block: rgb(231, 100, 100)
# char devices (ttys, /dev/urandom etc.)
char: rgb(230, 189, 87)
# fifos
fifo: rgb(180, 255, 255)
# opened sockets
socket: rgb(231, 100, 100)
# valid symlinks
symlink: rgb(59, 204, 255)
# broken symlinks
broken: rgb(140, 140, 140)

# Colors for menus, headers, footers etc.
# The same values are accepted.
# first color
header_first: rgb(45, 250, 209)
# second color
header_second: rgb(230, 189, 87)
# selected tab border
selected_border: rgb(45, 250, 209)
# non selected tab border
inert_border: rgb(120, 120, 120)
# palette of 4 elements, used in menus (second window)
palette_1: rgb(45, 250, 209)
palette_2: rgb(230, 189, 87)
palette_3: rgb(230, 167, 255)
palette_4: rgb(59, 204, 255)
