use crate::status::Status;

pub enum EventChar {
    ToggleHidden,
    CopyPaste,
    CutPaste,
    NewDir,
    NewFile,
    Chmod,
    Exec,
    Goto,
    Rename,
    ClearFlags,
    ToggleFlag,
    Shell,
    DeleteFile,
    OpenFile,
    Help,
    Search,
    RegexMatch,
    Quit,
    FlagAll,
    ReverseFlags,
    Jump,
    History,
    NvimFilepicker,
    Sort,
    Symlink,
    Preview,
    Shortcut,
}

impl EventChar {
    pub fn match_char(&self, status: &mut Status) {
        match *self {
            EventChar::ToggleHidden => status.event_toggle_hidden(),
            EventChar::CopyPaste => status.event_copy_paste(),
            EventChar::CutPaste => status.event_cur_paste(),
            EventChar::NewDir => status.event_new_dir(),
            EventChar::NewFile => status.event_new_file(),
            EventChar::Chmod => status.event_chmod(),
            EventChar::Exec => status.event_exec(),
            EventChar::Goto => status.event_goto(),
            EventChar::Rename => status.event_rename(),
            EventChar::ClearFlags => status.event_clear_flags(),
            EventChar::ToggleFlag => status.event_toggle_flag(),
            EventChar::Shell => status.event_shell(),
            EventChar::DeleteFile => status.event_delete_file(),
            EventChar::OpenFile => status.event_open_file(),
            EventChar::Help => status.event_help(),
            EventChar::Search => status.event_search(),
            EventChar::RegexMatch => status.event_regex_match(),
            EventChar::Quit => status.event_quit(),
            EventChar::FlagAll => status.event_flag_all(),
            EventChar::ReverseFlags => status.event_reverse_flags(),
            EventChar::Jump => status.event_jump(),
            EventChar::History => status.event_history(),
            EventChar::NvimFilepicker => status.event_nvim_filepicker(),
            EventChar::Sort => status.event_sort(),
            EventChar::Symlink => status.event_symlink(),
            EventChar::Preview => status.event_preview(),
            EventChar::Shortcut => status.event_shortcut(),
        }
    }
}
